# Generated by Django 5.2.7 on 2025-10-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='cnic_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='CNIC Number'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Facebook Profile'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='twitter_url',
            field=models.URLField(blank=True, verbose_name='Twitter Profile'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_documents',
            field=models.FileField(blank=True, null=True, upload_to='verification_docs/', verbose_name='Verification Documents'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, verbose_name='About Me'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, choices=[('islamabad', 'Islamabad'), ('rawalpindi', 'Rawalpindi'), ('karachi', 'Karachi'), ('lahore', 'Lahore'), ('faisalabad', 'Faisalabad'), ('multan', 'Multan'), ('peshawar', 'Peshawar'), ('quetta', 'Quetta'), ('sialkot', 'Sialkot'), ('gujranwala', 'Gujranwala'), ('bahawalpur', 'Bahawalpur'), ('sargodha', 'Sargodha'), ('sukkur', 'Sukkur'), ('larkana', 'Larkana'), ('hyderabad', 'Hyderabad'), ('abbottabad', 'Abbottabad'), ('mardan', 'Mardan'), ('kasur', 'Kasur'), ('dera ghazi khan', 'Dera Ghazi Khan'), ('sheikhupura', 'Sheikhupura')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Verified Organizer'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Phone Number'),
        ),
    ]
