# Generated by Django 5.2.7 on 2025-10-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_customuser_cnic_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_banners/', verbose_name='Background Banner Image'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cause_focus',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cause / Focus Area'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200, verbose_name='Organizer’s Name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram Profile'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mission',
            field=models.TextField(blank=True, verbose_name='Short Description / Mission'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='organization_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Organization / Group Name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='organization_role_type',
            field=models.CharField(blank=True, choices=[('organizer', 'Organizer'), ('volunteer_team', 'Volunteer Team'), ('awareness_group', 'Awareness Group')], max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='previous_activities',
            field=models.TextField(blank=True, verbose_name='Previous Activities'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Logo / Profile Image'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='responsible_person',
            field=models.CharField(blank=True, max_length=200, verbose_name='Responsible Person'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='undertaking_agreed',
            field=models.BooleanField(default=False, verbose_name='Agreed to Peaceful Conduct Undertaking'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='website_url',
            field=models.URLField(blank=True, verbose_name='Website'),
        ),
    ]
