# Generated by Django 5.2.7 on 2025-10-18 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Protest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Protest Title')),
                ('description', models.TextField(verbose_name='Detailed Description')),
                ('cause', models.CharField(choices=[('education', 'Education Rights'), ('healthcare', 'Healthcare Facilities'), ('electricity', 'Electricity & Utilities'), ('water', 'Water Shortage'), ('employment', 'Employment & Jobs'), ('human_rights', 'Human Rights'), ('women_rights', "Women's Rights"), ('minority_rights', 'Minority Rights'), ('price_hike', 'Price Hike & Inflation'), ('land_issues', 'Land & Property Issues'), ('political', 'Political Issues'), ('governance', 'Governance & Corruption'), ('environment', 'Environmental Issues'), ('other', 'Other Issues')], max_length=50, verbose_name='Protest Cause')),
                ('organizer_contact', models.CharField(blank=True, max_length=15, verbose_name='Organizer Contact Number')),
                ('city', models.CharField(choices=[('islamabad', 'Islamabad'), ('rawalpindi', 'Rawalpindi'), ('karachi', 'Karachi'), ('lahore', 'Lahore'), ('faisalabad', 'Faisalabad'), ('multan', 'Multan'), ('peshawar', 'Peshawar'), ('quetta', 'Quetta'), ('sialkot', 'Sialkot'), ('gujranwala', 'Gujranwala'), ('bahawalpur', 'Bahawalpur'), ('sargodha', 'Sargodha'), ('sukkur', 'Sukkur'), ('larkana', 'Larkana'), ('hyderabad', 'Hyderabad'), ('abbottabad', 'Abbottabad'), ('mardan', 'Mardan'), ('kasur', 'Kasur'), ('dera ghazi khan', 'Dera Ghazi Khan'), ('sheikhupura', 'Sheikhupura')], max_length=100, verbose_name='City')),
                ('specific_location', models.CharField(max_length=300, verbose_name='Specific Location/Venue')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('start_datetime', models.DateTimeField(verbose_name='Start Date & Time')),
                ('end_datetime', models.DateTimeField(verbose_name='End Date & Time')),
                ('expected_participants', models.PositiveIntegerField(default=0, verbose_name='Expected Number of Participants')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='protest_posters/', verbose_name='Protest Poster/Flyer')),
                ('supporting_documents', models.FileField(blank=True, null=True, upload_to='protest_documents/', verbose_name='Supporting Documents')),
                ('status', models.CharField(choices=[('pending', '⏳ Pending Approval'), ('approved', '✅ Approved'), ('rejected', '❌ Rejected'), ('upcoming', '📅 Upcoming'), ('ongoing', '🔴 Live - Ongoing'), ('completed', '✅ Completed'), ('cancelled', '❌ Cancelled')], default='pending', max_length=20)),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified Protest')),
                ('verification_notes', models.TextField(blank=True, verbose_name='Admin Verification Notes')),
                ('is_peaceful', models.BooleanField(default=True, verbose_name='Peaceful Protest')),
                ('safety_guidelines', models.TextField(blank=True, verbose_name='Safety Guidelines')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Total Views')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_protests', to=settings.AUTH_USER_MODEL, verbose_name='Organizer')),
            ],
            options={
                'verbose_name': 'Protest',
                'verbose_name_plural': 'Protests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('protest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supports', to='protests.protest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support',
                'verbose_name_plural': 'Supports',
                'unique_together': {('user', 'protest')},
            },
        ),
    ]
