# Generated by Django 5.2.7 on 2025-10-18 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('protests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtestUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(choices=[('info', 'ℹ️ General Update'), ('alert', '🚨 Important Alert'), ('location', '📍 Location Change'), ('time', '⏰ Timing Update'), ('safety', '🛡️ Safety Update'), ('success', '🎉 Success Update')], default='info', max_length=20, verbose_name='Update Type')),
                ('title', models.CharField(max_length=200, verbose_name='Update Title')),
                ('text', models.TextField(verbose_name='Update Details')),
                ('image', models.ImageField(blank=True, null=True, upload_to='update_images/', verbose_name='Update Image')),
                ('is_important', models.BooleanField(default=False, verbose_name='Important Update')),
                ('is_verified', models.BooleanField(default=True, verbose_name='Verified Information')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('protest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='protests.protest')),
            ],
        ),
    ]
